export type Country = {
  iso2: string;
  name: string;
  flag: string;
};

export const COUNTRIES: Country[] = [
  { iso2: 'AF', name: "Afghanistan", flag: "\ud83c\udde6\ud83c\uddeb" },
  { iso2: 'AL', name: "Albania", flag: "\ud83c\udde6\ud83c\uddf1" },
  { iso2: 'DZ', name: "Algeria", flag: "\ud83c\udde9\ud83c\uddff" },
  { iso2: 'AS', name: "American Samoa", flag: "\ud83c\udde6\ud83c\uddf8" },
  { iso2: 'AD', name: "Andorra", flag: "\ud83c\udde6\ud83c\udde9" },
  { iso2: 'AO', name: "Angola", flag: "\ud83c\udde6\ud83c\uddf4" },
  { iso2: 'AI', name: "Anguilla", flag: "\ud83c\udde6\ud83c\uddee" },
  { iso2: 'AQ', name: "Antarctica", flag: "\ud83c\udde6\ud83c\uddf6" },
  { iso2: 'AG', name: "Antigua and Barbuda", flag: "\ud83c\udde6\ud83c\uddec" },
  { iso2: 'AR', name: "Argentina", flag: "\ud83c\udde6\ud83c\uddf7" },
  { iso2: 'AM', name: "Armenia", flag: "\ud83c\udde6\ud83c\uddf2" },
  { iso2: 'AW', name: "Aruba", flag: "\ud83c\udde6\ud83c\uddfc" },
  { iso2: 'AU', name: "Australia", flag: "\ud83c\udde6\ud83c\uddfa" },
  { iso2: 'AT', name: "Austria", flag: "\ud83c\udde6\ud83c\uddf9" },
  { iso2: 'AZ', name: "Azerbaijan", flag: "\ud83c\udde6\ud83c\uddff" },
  { iso2: 'BS', name: "Bahamas", flag: "\ud83c\udde7\ud83c\uddf8" },
  { iso2: 'BH', name: "Bahrain", flag: "\ud83c\udde7\ud83c\udded" },
  { iso2: 'BD', name: "Bangladesh", flag: "\ud83c\udde7\ud83c\udde9" },
  { iso2: 'BB', name: "Barbados", flag: "\ud83c\udde7\ud83c\udde7" },
  { iso2: 'BY', name: "Belarus", flag: "\ud83c\udde7\ud83c\uddfe" },
  { iso2: 'BE', name: "Belgium", flag: "\ud83c\udde7\ud83c\uddea" },
  { iso2: 'BZ', name: "Belize", flag: "\ud83c\udde7\ud83c\uddff" },
  { iso2: 'BJ', name: "Benin", flag: "\ud83c\udde7\ud83c\uddef" },
  { iso2: 'BM', name: "Bermuda", flag: "\ud83c\udde7\ud83c\uddf2" },
  { iso2: 'BT', name: "Bhutan", flag: "\ud83c\udde7\ud83c\uddf9" },
  { iso2: 'BO', name: "Bolivia", flag: "\ud83c\udde7\ud83c\uddf4" },
  { iso2: 'BA', name: "Bosnia and Herzegovina", flag: "\ud83c\udde7\ud83c\udde6" },
  { iso2: 'BW', name: "Botswana", flag: "\ud83c\udde7\ud83c\uddfc" },
  { iso2: 'BV', name: "Bouvet Island", flag: "\ud83c\udde7\ud83c\uddfb" },
  { iso2: 'BR', name: "Brazil", flag: "\ud83c\udde7\ud83c\uddf7" },
  { iso2: 'IO', name: "British Indian Ocean Territory", flag: "\ud83c\uddee\ud83c\uddf4" },
  { iso2: 'VG', name: "British Virgin Islands", flag: "\ud83c\uddfb\ud83c\uddec" },
  { iso2: 'BN', name: "Brunei", flag: "\ud83c\udde7\ud83c\uddf3" },
  { iso2: 'BG', name: "Bulgaria", flag: "\ud83c\udde7\ud83c\uddec" },
  { iso2: 'BF', name: "Burkina Faso", flag: "\ud83c\udde7\ud83c\uddeb" },
  { iso2: 'BI', name: "Burundi", flag: "\ud83c\udde7\ud83c\uddee" },
  { iso2: 'KH', name: "Cambodia", flag: "\ud83c\uddf0\ud83c\udded" },
  { iso2: 'CM', name: "Cameroon", flag: "\ud83c\udde8\ud83c\uddf2" },
  { iso2: 'CA', name: "Canada", flag: "\ud83c\udde8\ud83c\udde6" },
  { iso2: 'CV', name: "Cape Verde", flag: "\ud83c\udde8\ud83c\uddfb" },
  { iso2: 'BQ', name: "Caribbean Netherlands", flag: "\ud83c\udde7\ud83c\uddf6" },
  { iso2: 'KY', name: "Cayman Islands", flag: "\ud83c\uddf0\ud83c\uddfe" },
  { iso2: 'CF', name: "Central African Republic", flag: "\ud83c\udde8\ud83c\uddeb" },
  { iso2: 'TD', name: "Chad", flag: "\ud83c\uddf9\ud83c\udde9" },
  { iso2: 'CL', name: "Chile", flag: "\ud83c\udde8\ud83c\uddf1" },
  { iso2: 'CN', name: "China", flag: "\ud83c\udde8\ud83c\uddf3" },
  { iso2: 'CX', name: "Christmas Island", flag: "\ud83c\udde8\ud83c\uddfd" },
  { iso2: 'CC', name: "Cocos (Keeling) Islands", flag: "\ud83c\udde8\ud83c\udde8" },
  { iso2: 'CO', name: "Colombia", flag: "\ud83c\udde8\ud83c\uddf4" },
  { iso2: 'KM', name: "Comoros", flag: "\ud83c\uddf0\ud83c\uddf2" },
  { iso2: 'CK', name: "Cook Islands", flag: "\ud83c\udde8\ud83c\uddf0" },
  { iso2: 'CR', name: "Costa Rica", flag: "\ud83c\udde8\ud83c\uddf7" },
  { iso2: 'HR', name: "Croatia", flag: "\ud83c\udded\ud83c\uddf7" },
  { iso2: 'CU', name: "Cuba", flag: "\ud83c\udde8\ud83c\uddfa" },
  { iso2: 'CW', name: "Cura\u00e7ao", flag: "\ud83c\udde8\ud83c\uddfc" },
  { iso2: 'CY', name: "Cyprus", flag: "\ud83c\udde8\ud83c\uddfe" },
  { iso2: 'CZ', name: "Czechia", flag: "\ud83c\udde8\ud83c\uddff" },
  { iso2: 'CD', name: "DR Congo", flag: "\ud83c\udde8\ud83c\udde9" },
  { iso2: 'DK', name: "Denmark", flag: "\ud83c\udde9\ud83c\uddf0" },
  { iso2: 'DJ', name: "Djibouti", flag: "\ud83c\udde9\ud83c\uddef" },
  { iso2: 'DM', name: "Dominica", flag: "\ud83c\udde9\ud83c\uddf2" },
  { iso2: 'DO', name: "Dominican Republic", flag: "\ud83c\udde9\ud83c\uddf4" },
  { iso2: 'EC', name: "Ecuador", flag: "\ud83c\uddea\ud83c\udde8" },
  { iso2: 'EG', name: "Egypt", flag: "\ud83c\uddea\ud83c\uddec" },
  { iso2: 'SV', name: "El Salvador", flag: "\ud83c\uddf8\ud83c\uddfb" },
  { iso2: 'GQ', name: "Equatorial Guinea", flag: "\ud83c\uddec\ud83c\uddf6" },
  { iso2: 'ER', name: "Eritrea", flag: "\ud83c\uddea\ud83c\uddf7" },
  { iso2: 'EE', name: "Estonia", flag: "\ud83c\uddea\ud83c\uddea" },
  { iso2: 'SZ', name: "Eswatini", flag: "\ud83c\uddf8\ud83c\uddff" },
  { iso2: 'ET', name: "Ethiopia", flag: "\ud83c\uddea\ud83c\uddf9" },
  { iso2: 'FK', name: "Falkland Islands", flag: "\ud83c\uddeb\ud83c\uddf0" },
  { iso2: 'FO', name: "Faroe Islands", flag: "\ud83c\uddeb\ud83c\uddf4" },
  { iso2: 'FJ', name: "Fiji", flag: "\ud83c\uddeb\ud83c\uddef" },
  { iso2: 'FI', name: "Finland", flag: "\ud83c\uddeb\ud83c\uddee" },
  { iso2: 'FR', name: "France", flag: "\ud83c\uddeb\ud83c\uddf7" },
  { iso2: 'GF', name: "French Guiana", flag: "\ud83c\uddec\ud83c\uddeb" },
  { iso2: 'PF', name: "French Polynesia", flag: "\ud83c\uddf5\ud83c\uddeb" },
  { iso2: 'TF', name: "French Southern and Antarctic Lands", flag: "\ud83c\uddf9\ud83c\uddeb" },
  { iso2: 'GA', name: "Gabon", flag: "\ud83c\uddec\ud83c\udde6" },
  { iso2: 'GM', name: "Gambia", flag: "\ud83c\uddec\ud83c\uddf2" },
  { iso2: 'GE', name: "Georgia", flag: "\ud83c\uddec\ud83c\uddea" },
  { iso2: 'DE', name: "Germany", flag: "\ud83c\udde9\ud83c\uddea" },
  { iso2: 'GH', name: "Ghana", flag: "\ud83c\uddec\ud83c\udded" },
  { iso2: 'GI', name: "Gibraltar", flag: "\ud83c\uddec\ud83c\uddee" },
  { iso2: 'GR', name: "Greece", flag: "\ud83c\uddec\ud83c\uddf7" },
  { iso2: 'GL', name: "Greenland", flag: "\ud83c\uddec\ud83c\uddf1" },
  { iso2: 'GD', name: "Grenada", flag: "\ud83c\uddec\ud83c\udde9" },
  { iso2: 'GP', name: "Guadeloupe", flag: "\ud83c\uddec\ud83c\uddf5" },
  { iso2: 'GU', name: "Guam", flag: "\ud83c\uddec\ud83c\uddfa" },
  { iso2: 'GT', name: "Guatemala", flag: "\ud83c\uddec\ud83c\uddf9" },
  { iso2: 'GG', name: "Guernsey", flag: "\ud83c\uddec\ud83c\uddec" },
  { iso2: 'GN', name: "Guinea", flag: "\ud83c\uddec\ud83c\uddf3" },
  { iso2: 'GW', name: "Guinea-Bissau", flag: "\ud83c\uddec\ud83c\uddfc" },
  { iso2: 'GY', name: "Guyana", flag: "\ud83c\uddec\ud83c\uddfe" },
  { iso2: 'HT', name: "Haiti", flag: "\ud83c\udded\ud83c\uddf9" },
  { iso2: 'HM', name: "Heard Island and McDonald Islands", flag: "\ud83c\udded\ud83c\uddf2" },
  { iso2: 'HN', name: "Honduras", flag: "\ud83c\udded\ud83c\uddf3" },
  { iso2: 'HK', name: "Hong Kong", flag: "\ud83c\udded\ud83c\uddf0" },
  { iso2: 'HU', name: "Hungary", flag: "\ud83c\udded\ud83c\uddfa" },
  { iso2: 'IS', name: "Iceland", flag: "\ud83c\uddee\ud83c\uddf8" },
  { iso2: 'IN', name: "India", flag: "\ud83c\uddee\ud83c\uddf3" },
  { iso2: 'ID', name: "Indonesia", flag: "\ud83c\uddee\ud83c\udde9" },
  { iso2: 'IR', name: "Iran", flag: "\ud83c\uddee\ud83c\uddf7" },
  { iso2: 'IQ', name: "Iraq", flag: "\ud83c\uddee\ud83c\uddf6" },
  { iso2: 'IE', name: "Ireland", flag: "\ud83c\uddee\ud83c\uddea" },
  { iso2: 'IM', name: "Isle of Man", flag: "\ud83c\uddee\ud83c\uddf2" },
  { iso2: 'IL', name: "Israel", flag: "\ud83c\uddee\ud83c\uddf1" },
  { iso2: 'IT', name: "Italy", flag: "\ud83c\uddee\ud83c\uddf9" },
  { iso2: 'CI', name: "Ivory Coast", flag: "\ud83c\udde8\ud83c\uddee" },
  { iso2: 'JM', name: "Jamaica", flag: "\ud83c\uddef\ud83c\uddf2" },
  { iso2: 'JP', name: "Japan", flag: "\ud83c\uddef\ud83c\uddf5" },
  { iso2: 'JE', name: "Jersey", flag: "\ud83c\uddef\ud83c\uddea" },
  { iso2: 'JO', name: "Jordan", flag: "\ud83c\uddef\ud83c\uddf4" },
  { iso2: 'KZ', name: "Kazakhstan", flag: "\ud83c\uddf0\ud83c\uddff" },
  { iso2: 'KE', name: "Kenya", flag: "\ud83c\uddf0\ud83c\uddea" },
  { iso2: 'KI', name: "Kiribati", flag: "\ud83c\uddf0\ud83c\uddee" },
  { iso2: 'XK', name: "Kosovo", flag: "\ud83c\uddfd\ud83c\uddf0" },
  { iso2: 'KW', name: "Kuwait", flag: "\ud83c\uddf0\ud83c\uddfc" },
  { iso2: 'KG', name: "Kyrgyzstan", flag: "\ud83c\uddf0\ud83c\uddec" },
  { iso2: 'LA', name: "Laos", flag: "\ud83c\uddf1\ud83c\udde6" },
  { iso2: 'LV', name: "Latvia", flag: "\ud83c\uddf1\ud83c\uddfb" },
  { iso2: 'LB', name: "Lebanon", flag: "\ud83c\uddf1\ud83c\udde7" },
  { iso2: 'LS', name: "Lesotho", flag: "\ud83c\uddf1\ud83c\uddf8" },
  { iso2: 'LR', name: "Liberia", flag: "\ud83c\uddf1\ud83c\uddf7" },
  { iso2: 'LY', name: "Libya", flag: "\ud83c\uddf1\ud83c\uddfe" },
  { iso2: 'LI', name: "Liechtenstein", flag: "\ud83c\uddf1\ud83c\uddee" },
  { iso2: 'LT', name: "Lithuania", flag: "\ud83c\uddf1\ud83c\uddf9" },
  { iso2: 'LU', name: "Luxembourg", flag: "\ud83c\uddf1\ud83c\uddfa" },
  { iso2: 'MO', name: "Macau", flag: "\ud83c\uddf2\ud83c\uddf4" },
  { iso2: 'MG', name: "Madagascar", flag: "\ud83c\uddf2\ud83c\uddec" },
  { iso2: 'MW', name: "Malawi", flag: "\ud83c\uddf2\ud83c\uddfc" },
  { iso2: 'MY', name: "Malaysia", flag: "\ud83c\uddf2\ud83c\uddfe" },
  { iso2: 'MV', name: "Maldives", flag: "\ud83c\uddf2\ud83c\uddfb" },
  { iso2: 'ML', name: "Mali", flag: "\ud83c\uddf2\ud83c\uddf1" },
  { iso2: 'MT', name: "Malta", flag: "\ud83c\uddf2\ud83c\uddf9" },
  { iso2: 'MH', name: "Marshall Islands", flag: "\ud83c\uddf2\ud83c\udded" },
  { iso2: 'MQ', name: "Martinique", flag: "\ud83c\uddf2\ud83c\uddf6" },
  { iso2: 'MR', name: "Mauritania", flag: "\ud83c\uddf2\ud83c\uddf7" },
  { iso2: 'MU', name: "Mauritius", flag: "\ud83c\uddf2\ud83c\uddfa" },
  { iso2: 'YT', name: "Mayotte", flag: "\ud83c\uddfe\ud83c\uddf9" },
  { iso2: 'MX', name: "Mexico", flag: "\ud83c\uddf2\ud83c\uddfd" },
  { iso2: 'FM', name: "Micronesia", flag: "\ud83c\uddeb\ud83c\uddf2" },
  { iso2: 'MD', name: "Moldova", flag: "\ud83c\uddf2\ud83c\udde9" },
  { iso2: 'MC', name: "Monaco", flag: "\ud83c\uddf2\ud83c\udde8" },
  { iso2: 'MN', name: "Mongolia", flag: "\ud83c\uddf2\ud83c\uddf3" },
  { iso2: 'ME', name: "Montenegro", flag: "\ud83c\uddf2\ud83c\uddea" },
  { iso2: 'MS', name: "Montserrat", flag: "\ud83c\uddf2\ud83c\uddf8" },
  { iso2: 'MA', name: "Morocco", flag: "\ud83c\uddf2\ud83c\udde6" },
  { iso2: 'MZ', name: "Mozambique", flag: "\ud83c\uddf2\ud83c\uddff" },
  { iso2: 'MM', name: "Myanmar", flag: "\ud83c\uddf2\ud83c\uddf2" },
  { iso2: 'NA', name: "Namibia", flag: "\ud83c\uddf3\ud83c\udde6" },
  { iso2: 'NR', name: "Nauru", flag: "\ud83c\uddf3\ud83c\uddf7" },
  { iso2: 'NP', name: "Nepal", flag: "\ud83c\uddf3\ud83c\uddf5" },
  { iso2: 'NL', name: "Netherlands", flag: "\ud83c\uddf3\ud83c\uddf1" },
  { iso2: 'NC', name: "New Caledonia", flag: "\ud83c\uddf3\ud83c\udde8" },
  { iso2: 'NZ', name: "New Zealand", flag: "\ud83c\uddf3\ud83c\uddff" },
  { iso2: 'NI', name: "Nicaragua", flag: "\ud83c\uddf3\ud83c\uddee" },
  { iso2: 'NE', name: "Niger", flag: "\ud83c\uddf3\ud83c\uddea" },
  { iso2: 'NG', name: "Nigeria", flag: "\ud83c\uddf3\ud83c\uddec" },
  { iso2: 'NU', name: "Niue", flag: "\ud83c\uddf3\ud83c\uddfa" },
  { iso2: 'NF', name: "Norfolk Island", flag: "\ud83c\uddf3\ud83c\uddeb" },
  { iso2: 'KP', name: "North Korea", flag: "\ud83c\uddf0\ud83c\uddf5" },
  { iso2: 'MK', name: "North Macedonia", flag: "\ud83c\uddf2\ud83c\uddf0" },
  { iso2: 'MP', name: "Northern Mariana Islands", flag: "\ud83c\uddf2\ud83c\uddf5" },
  { iso2: 'NO', name: "Norway", flag: "\ud83c\uddf3\ud83c\uddf4" },
  { iso2: 'OM', name: "Oman", flag: "\ud83c\uddf4\ud83c\uddf2" },
  { iso2: 'PK', name: "Pakistan", flag: "\ud83c\uddf5\ud83c\uddf0" },
  { iso2: 'PW', name: "Palau", flag: "\ud83c\uddf5\ud83c\uddfc" },
  { iso2: 'PS', name: "Palestine", flag: "\ud83c\uddf5\ud83c\uddf8" },
  { iso2: 'PA', name: "Panama", flag: "\ud83c\uddf5\ud83c\udde6" },
  { iso2: 'PG', name: "Papua New Guinea", flag: "\ud83c\uddf5\ud83c\uddec" },
  { iso2: 'PY', name: "Paraguay", flag: "\ud83c\uddf5\ud83c\uddfe" },
  { iso2: 'PE', name: "Peru", flag: "\ud83c\uddf5\ud83c\uddea" },
  { iso2: 'PH', name: "Philippines", flag: "\ud83c\uddf5\ud83c\udded" },
  { iso2: 'PN', name: "Pitcairn Islands", flag: "\ud83c\uddf5\ud83c\uddf3" },
  { iso2: 'PL', name: "Poland", flag: "\ud83c\uddf5\ud83c\uddf1" },
  { iso2: 'PT', name: "Portugal", flag: "\ud83c\uddf5\ud83c\uddf9" },
  { iso2: 'PR', name: "Puerto Rico", flag: "\ud83c\uddf5\ud83c\uddf7" },
  { iso2: 'QA', name: "Qatar", flag: "\ud83c\uddf6\ud83c\udde6" },
  { iso2: 'CG', name: "Republic of the Congo", flag: "\ud83c\udde8\ud83c\uddec" },
  { iso2: 'RO', name: "Romania", flag: "\ud83c\uddf7\ud83c\uddf4" },
  { iso2: 'RU', name: "Russia", flag: "\ud83c\uddf7\ud83c\uddfa" },
  { iso2: 'RW', name: "Rwanda", flag: "\ud83c\uddf7\ud83c\uddfc" },
  { iso2: 'RE', name: "R\u00e9union", flag: "\ud83c\uddf7\ud83c\uddea" },
  { iso2: 'BL', name: "Saint Barth\u00e9lemy", flag: "\ud83c\udde7\ud83c\uddf1" },
  { iso2: 'SH', name: "Saint Helena, Ascension and Tristan da Cunha", flag: "\ud83c\uddf8\ud83c\udded" },
  { iso2: 'KN', name: "Saint Kitts and Nevis", flag: "\ud83c\uddf0\ud83c\uddf3" },
  { iso2: 'LC', name: "Saint Lucia", flag: "\ud83c\uddf1\ud83c\udde8" },
  { iso2: 'MF', name: "Saint Martin", flag: "\ud83c\uddf2\ud83c\uddeb" },
  { iso2: 'PM', name: "Saint Pierre and Miquelon", flag: "\ud83c\uddf5\ud83c\uddf2" },
  { iso2: 'VC', name: "Saint Vincent and the Grenadines", flag: "\ud83c\uddfb\ud83c\udde8" },
  { iso2: 'WS', name: "Samoa", flag: "\ud83c\uddfc\ud83c\uddf8" },
  { iso2: 'SM', name: "San Marino", flag: "\ud83c\uddf8\ud83c\uddf2" },
  { iso2: 'SA', name: "Saudi Arabia", flag: "\ud83c\uddf8\ud83c\udde6" },
  { iso2: 'SN', name: "Senegal", flag: "\ud83c\uddf8\ud83c\uddf3" },
  { iso2: 'RS', name: "Serbia", flag: "\ud83c\uddf7\ud83c\uddf8" },
  { iso2: 'SC', name: "Seychelles", flag: "\ud83c\uddf8\ud83c\udde8" },
  { iso2: 'SL', name: "Sierra Leone", flag: "\ud83c\uddf8\ud83c\uddf1" },
  { iso2: 'SG', name: "Singapore", flag: "\ud83c\uddf8\ud83c\uddec" },
  { iso2: 'SX', name: "Sint Maarten", flag: "\ud83c\uddf8\ud83c\uddfd" },
  { iso2: 'SK', name: "Slovakia", flag: "\ud83c\uddf8\ud83c\uddf0" },
  { iso2: 'SI', name: "Slovenia", flag: "\ud83c\uddf8\ud83c\uddee" },
  { iso2: 'SB', name: "Solomon Islands", flag: "\ud83c\uddf8\ud83c\udde7" },
  { iso2: 'SO', name: "Somalia", flag: "\ud83c\uddf8\ud83c\uddf4" },
  { iso2: 'ZA', name: "South Africa", flag: "\ud83c\uddff\ud83c\udde6" },
  { iso2: 'GS', name: "South Georgia", flag: "\ud83c\uddec\ud83c\uddf8" },
  { iso2: 'KR', name: "South Korea", flag: "\ud83c\uddf0\ud83c\uddf7" },
  { iso2: 'SS', name: "South Sudan", flag: "\ud83c\uddf8\ud83c\uddf8" },
  { iso2: 'ES', name: "Spain", flag: "\ud83c\uddea\ud83c\uddf8" },
  { iso2: 'LK', name: "Sri Lanka", flag: "\ud83c\uddf1\ud83c\uddf0" },
  { iso2: 'SD', name: "Sudan", flag: "\ud83c\uddf8\ud83c\udde9" },
  { iso2: 'SR', name: "Suriname", flag: "\ud83c\uddf8\ud83c\uddf7" },
  { iso2: 'SJ', name: "Svalbard and Jan Mayen", flag: "\ud83c\uddf8\ud83c\uddef" },
  { iso2: 'SE', name: "Sweden", flag: "\ud83c\uddf8\ud83c\uddea" },
  { iso2: 'CH', name: "Switzerland", flag: "\ud83c\udde8\ud83c\udded" },
  { iso2: 'SY', name: "Syria", flag: "\ud83c\uddf8\ud83c\uddfe" },
  { iso2: 'ST', name: "S\u00e3o Tom\u00e9 and Pr\u00edncipe", flag: "\ud83c\uddf8\ud83c\uddf9" },
  { iso2: 'TW', name: "Taiwan", flag: "\ud83c\uddf9\ud83c\uddfc" },
  { iso2: 'TJ', name: "Tajikistan", flag: "\ud83c\uddf9\ud83c\uddef" },
  { iso2: 'TZ', name: "Tanzania", flag: "\ud83c\uddf9\ud83c\uddff" },
  { iso2: 'TH', name: "Thailand", flag: "\ud83c\uddf9\ud83c\udded" },
  { iso2: 'TL', name: "Timor-Leste", flag: "\ud83c\uddf9\ud83c\uddf1" },
  { iso2: 'TG', name: "Togo", flag: "\ud83c\uddf9\ud83c\uddec" },
  { iso2: 'TK', name: "Tokelau", flag: "\ud83c\uddf9\ud83c\uddf0" },
  { iso2: 'TO', name: "Tonga", flag: "\ud83c\uddf9\ud83c\uddf4" },
  { iso2: 'TT', name: "Trinidad and Tobago", flag: "\ud83c\uddf9\ud83c\uddf9" },
  { iso2: 'TN', name: "Tunisia", flag: "\ud83c\uddf9\ud83c\uddf3" },
  { iso2: 'TR', name: "Turkey", flag: "\ud83c\uddf9\ud83c\uddf7" },
  { iso2: 'TM', name: "Turkmenistan", flag: "\ud83c\uddf9\ud83c\uddf2" },
  { iso2: 'TC', name: "Turks and Caicos Islands", flag: "\ud83c\uddf9\ud83c\udde8" },
  { iso2: 'TV', name: "Tuvalu", flag: "\ud83c\uddf9\ud83c\uddfb" },
  { iso2: 'UG', name: "Uganda", flag: "\ud83c\uddfa\ud83c\uddec" },
  { iso2: 'UA', name: "Ukraine", flag: "\ud83c\uddfa\ud83c\udde6" },
  { iso2: 'AE', name: "United Arab Emirates", flag: "\ud83c\udde6\ud83c\uddea" },
  { iso2: 'GB', name: "United Kingdom", flag: "\ud83c\uddec\ud83c\udde7" },
  { iso2: 'US', name: "United States", flag: "\ud83c\uddfa\ud83c\uddf8" },
  { iso2: 'UM', name: "United States Minor Outlying Islands", flag: "\ud83c\uddfa\ud83c\uddf2" },
  { iso2: 'VI', name: "United States Virgin Islands", flag: "\ud83c\uddfb\ud83c\uddee" },
  { iso2: 'UY', name: "Uruguay", flag: "\ud83c\uddfa\ud83c\uddfe" },
  { iso2: 'UZ', name: "Uzbekistan", flag: "\ud83c\uddfa\ud83c\uddff" },
  { iso2: 'VU', name: "Vanuatu", flag: "\ud83c\uddfb\ud83c\uddfa" },
  { iso2: 'VA', name: "Vatican City", flag: "\ud83c\uddfb\ud83c\udde6" },
  { iso2: 'VE', name: "Venezuela", flag: "\ud83c\uddfb\ud83c\uddea" },
  { iso2: 'VN', name: "Vietnam", flag: "\ud83c\uddfb\ud83c\uddf3" },
  { iso2: 'WF', name: "Wallis and Futuna", flag: "\ud83c\uddfc\ud83c\uddeb" },
  { iso2: 'EH', name: "Western Sahara", flag: "\ud83c\uddea\ud83c\udded" },
  { iso2: 'YE', name: "Yemen", flag: "\ud83c\uddfe\ud83c\uddea" },
  { iso2: 'ZM', name: "Zambia", flag: "\ud83c\uddff\ud83c\uddf2" },
  { iso2: 'ZW', name: "Zimbabwe", flag: "\ud83c\uddff\ud83c\uddfc" },
  { iso2: 'AX', name: "\u00c5land Islands", flag: "\ud83c\udde6\ud83c\uddfd" },
];

export const getCountryByIso2 = (iso2: string) =>
  COUNTRIES.find((country) => country.iso2 === iso2.toUpperCase()) ?? null;
